name: Peacekeeper
main: com.gmail.sintinium.peacekeeper.Peacekeeper
version: 0.98
depend: [SQLibrary]
softdepend: [ScoreboardStats, Essentials, SuperTrails]
commands:
  peacekeeper:
    aliases: [pk]
    description: General command for basic plugin functions such as /reload
  report:
    description: Used to report an issue
    permission: peacekeeper.command.report
  suspend:
    description: Suspends a player from the server
    permission: peacekeeper.command.suspend
    usage: §4Syntax error! Usage §r§c/suspend <player> <reason>
  mute:
    description: Mutes a player from chat
    permission: peacekeeper.command.mute
    usage: §4Syntax error! Usage §r§c/mute <player> <reason>
  release:
    description: Releases a user, including jail, mute, and bans
    permission: peacekeeper.release
    usage: §4Syntax error! Usage §r§c/release <player|IP>
  playerinfo:
    description: Get a player's information
    permission: peacekeeper.command.playerinfo
    usage: Syntax error! Usage §r§c/playerinfo <player>!
  records:
    description: Display all of a users records
    permission: peacekeeper.command.records
    usage: Syntax error! Usage §r§c/records 'ID|Player|UUID|IP' <ID|Player|UUID|IP>
permissions:
  peacekeeper.*:
    description: Give access to all commands and actions within the Peacekeeper plugin
    default: op
    children:
        peacekeeper.command.*: true
        peacekeeper.info.ip: true
        peacekeeper.release.notify: true
  peacekeeper.command.*:
    description: Has permission to use all manual commands
    default: op
    children:
        peacekeeper.command.peacekeeper.reload: true
        peacekeeper.command.report: true
        peacekeeper.command.info: true
        peacekeeper.command.records: true
        peacekeeper.command.records.delete: true
        peacekeeper.command.mute: true
        peacekeeper.command.tempban: true
        peacekeeper.command.permban: true
        peacekeeper.command.ipban: true
        peacekeeper.command.release: true
        peacekeeper.command.vanish: true
  peacekeeper.command.peacekeeper.reload:
    description: Has permission to reload config via /pk reload
    default: op
  peacekeeper.command.report:
    description: Has permission to report issues with the server
    default: op
  peacekeeper.command.info:
    description: Has permission to view a player's info
    default: op
  peacekeeper.command.records:
    description: Has permission to view a player's records
    default: op
  peacekeeper.command.records.delete:
    description: Has permission to delete records from database
    default: op
  peacekeeper.info.ip:
    description: Has permission to view someone's ip when using /playerinfo
    default: op
  peacekeeper.command.mute:
    description: Has permission to mute a user.
    default: op
  peacekeeper.command.suspend:
    description: Has permission to suspend a user
    default: op
  peacekeeper.command.permban:
    description: Has permission to perm ban a user
    default: op
  peacekeeper.command.ipban:
    description: Has permission to ip ban a user
    default: op
  peacekeeper.command.release:
    description: Has permission to remove all punishments from a user
    default: op
  peacekeeper.release.notify:
    description: Has permission to see when someone is released
    default: op
  peacekeeper.command.vanish:
    description: Has permission to use the vanish command
    default: op
  peacekeeper.command.vanish.cansee:
    description: Has permission to see vanished players
    default: op