name: Peacekeeper
main: com.gmail.sintinium.peacekeeper.Peacekeeper
version: 1.3
depend: [SQLibrary]
loadbefore: [Essentials]
softdepend: [ScoreboardStats, Essentials]
commands:
  peacekeeper:
    aliases: [pk]
    description: General command for basic plugin functions such as /reload
  report:
    description: Used to report an issue
    permission: peacekeeper.command.report
    usage: §4Syntax error! Usage §r§c/report <player(s)...>
  viewreports:
    aliases: [vreport, reports]
    description: Used to view/modify reports
    permission: peacekeeper.command.viewreports
    usage: §3Use §b'/viewreports ?' §3for help and usages
  warn:
    description: Warns a player
    permission: peacekeeper.command.warn
    usage: §4Syntax error! Usage §r§c/warn <player> <reason>
  suspend:
    aliases: [tempban]
    description: Suspends a player from the server
    permission: peacekeeper.command.suspend
    usage: §4Syntax error! Usage §r§c/suspend <player> <reason>
  mute:
    description: Mutes a player from chat
    permission: peacekeeper.command.mute
    usage: §4Syntax error! Usage §r§c/mute <player> <reason>
  ban:
    description: Permanently bans a player
    permission: peacekeeper.command.ban
    usage: §4Syntax error! Usage §r§c/banip <player> <reason>
  banip:
    aliases: [ipban, suspendip, ipsuspend]
    description: Bans an IP
    permission: peacekeeper.command.banip
    usage: §4Syntax error! Usage §r§c/banip <player|IP> <reason>
  release:
    description: Releases a user, including jail, mute, and bans
    permission: peacekeeper.release
    usage: §4Syntax error! Usage §r§c/release <player|IP>
  playerinfo:
    aliases: [pinfo, plookup]
    description: Get a player's information
    permission: peacekeeper.command.playerinfo
    usage: §4Syntax error! Usage §r§c/playerinfo <player>!
  records:
    aliases: [rec]
    description: Display all of a users records
    permission: peacekeeper.command.records
    usage: §3Use §b'/records ?' §3for help and usages
permissions:
  peacekeeper.*:
    description: Give access to all commands and actions within the Peacekeeper plugin
    default: op
    children:
        peacekeeper.command.*: true
        peacekeeper.info.ip: true
        peacekeeper.release.notify: true
        peacekeeper.filter.bypass: true
        peacekeeper.filter.broadcast: true
  peacekeeper.command.*:
    description: Has permission to use all manual commands
    default: op
    children:
        peacekeeper.command.overridepunishment: true
        peacekeeper.command.peacekeeper.reload: true
        peacekeeper.command.report: true
        peacekeeper.command.viewreports: true
        peacekeeper.command.viewreports.delete: true
        peacekeeper.command.viewreports.deleteall: true
        peacekeeper.command.view: true
        peacekeeper.command.delete: true
        peacekeeper.command.info: true
        peacekeeper.command.records: true
        peacekeeper.command.records.delete: true
        peacekeeper.command.records.deleteall: true
        peacekeeper.command.warn: true
        peacekeeper.command.mute: true
        peacekeeper.command.suspend: true
        peacekeeper.command.ban: true
        peacekeeper.command.banip: true
        peacekeeper.command.release: true
        peacekeeper.command.vanish: true
  peacekeeper.filter.broadcast:
    description: Has permission to view blocked messages
    default: op
  peacekeeper.filter.bypass:
    description: Has permission to bypass the chat filter
    default: op
  peacekeeper.command.overridepunishment:
    description: Has permission to override another admin's punishments
    default: op
  peacekeeper.command.peacekeeper.reload:
    description: Has permission to reload config via /pk reload
    default: op
  peacekeeper.command.report:
    description: Has permission to report issues with the server
    default: op
  peacekeeper.command.viewreports:
    description: Has permission to view reports
    default: op
  peacekeeper.command.viewreports.delete:
    description: Has permission to delete reports
    default: op
  peacekeeper.command.viewreports.deleteall:
    description: Has permission to delete all reports
    default: op
  peacekeeper.command.info:
    description: Has permission to view a player's info
    default: op
  peacekeeper.command.records:
    description: Has permission to view a player's records
    default: op
  peacekeeper.command.records.delete:
    description: Has permission to delete records from database
    default: op
  peacekeeper.command.records.deleteall:
    description: Has permission to delete all records for given user
    default: op
  peacekeeper.info.ip:
    description: Has permission to view someone's ip when using /playerinfo
    default: op
  peacekeeper.command.warn:
    description: Has permission to mute a user.
    default: op
  peacekeeper.command.mute:
    description: Has permission to mute a user.
    default: op
  peacekeeper.command.suspend:
    description: Has permission to suspend a user
    default: op
  peacekeeper.command.ban:
    description: Has permission to permanently ban a user
    default: op
  peacekeeper.command.banip:
    description: Has permission to ip ban a user
    default: op
  peacekeeper.command.release:
    description: Has permission to remove all punishments from a user
    default: op
  peacekeeper.command.vanish:
    description: Has permission to use the vanish command
    default: op
  peacekeeper.command.vanish.cansee:
    description: Has permission to see vanished players
    default: op
  peacekeeper.broadcast:
    description: Has permission to see when someone is punished, released, or someone deletes a record or report
    default: op