#Times are set by the following (s - second, m - minute, h - hour, d - day, w - week, y - 365 year). Note there are no month times.
#Examples 1h5s - 1 hour 5 seconds, 1h1h10m - 2 hours 10 minutes, 1y5w2d - 1 year 5 weeks and 2 days.

#Note: This plugin automatically calculates time based on the default 'length' it will scale the times based on how many categories and how many
#previous offenses
Types:
  Suspend: #Categories for suspension.
    Harassment:
      description: Harassment
      length: 1h
    Griefing:
      description: Griefing
      length: 1w
    Hacking:
      description: Hacking
      length: 1w
    Exploit:
      description: Exploiting Things
      length: 1w
    Stealing:
      description: Stealing
      length: 5d
    BanEvasion:
      description: Ban-Evasion/Alts
      length: 4w
    DDoS:
      description: Threats/Use of DDoS
      length: 26w
    Trolling:
      description: Malicious Trolling
      length: 1w
  Mute: #Categories for muting
    CapsSpam:
      description: Excessive Caps
      length: 10m
    Spamming:
      description: Chat Spam
      length: 15m
    Cursing:
      description: Inappropriate Language
      length: 30m
    Offensive:
      description: Offensive Language
      length: 30m
    Arguments:
      description: Argument
      length: 30m
    Advertising:
      description: Advertising
      length: 1h
  Report: #Categories to report for
    Inappropriate:
      description: Inappropriate or offensive content
    Cursing:
      description: Cursing, verbal abuse, or spamming
    Disrespect:
      description: Disrespecting staff or other users
    Drama:
      description: Causing drama or heated arguments
    Rules:
      description: Breaking division rules (such as griefing)
    Advertising:
      description: Advertising
    Hacking:
      description: Hacking or using exploits
    StaffAbuse:
      description: (Staff) Power abuse
    StaffInjustice:
      description: (Staff) Injustice
    StaffRules:
      description: (Staff) Breaking rules
    StaffRude:
      description: (Staff) Acting rude or unprofessional
    Other:
      description: (All) Other (please include details in description)